### ISSUE TITLE
Program is not running

### ISSUE THREAD

**Issue by anju-infracloud** [RavirajPawar/UrlShortner#1]
I ran `curl -X POST http://127.0.0.1:5000/ -d '{"url": "facebook.com"}'` this command but it threw following error.

`Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/url_ashortner_app/app.py", line 11, in index
    url = request.form['url']
  File "/usr/local/lib/python3.8/site-packages/werkzeug/datastructures.py", line 377, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
KeyError: 'url'`

can you please update README with correct commands or fix the errors?

**Comment by RavirajPawar** [comment]
you can try **curl -d "url=http://facebook.com" http://127.0.0.1:5000/**. Here header **_Content-Type: application/x-www-form-urlencoded_**.  You will get an HTML response for this. If you want to make my response as JSON. I will need to update the code and rebuild the docker image in that case. If you want let me know.

If you have downloaded docker image then you can see UI for same at your **localhost:5000**

**Comment by RavirajPawar** [comment]
Hope your issue is cleared. If you want any further discussion, please open it again.
